### ISSUE TITLE
Detecting Crazyflie and a target using kinect one

### ISSUE THREAD

**Issue by crazynirmal** [FairchildC/ROS-Robotics-By-Example-2nd-Edition#1]
I am trying to fly the crazyflie 2.0 quadcopter by using kinect xbox one. I have setup the system as given in the book "ROS Robotics By Example - Second Edition".
But I am facing problem when execute "detect_crazyflie.py" in https://github.com/FairchildC/ROS-Robotics-By-Example-2nd-Edition/tree/master/Chapter9_code/crazyflie_autonomous/scripts. I have followed all the steps as given in the book.
The error is shown as follows,

[ERROR] [1568893593.628256]: bad callback: <bound method Detector.image_callback of <__main__.Detector instance at 0x7f3a6ccd1bd8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "detect_crazyflie.py", line 87, in image_callback
    contours, heirarchy = cv2.findContours(mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
ValueError: too many values to unpack

Thank you.

**Comment by FairchildC** [comment]
The error may be due to the version of OpenCV that you are using.  ROS Kinetic Kame uses OpenCV version 3 as its default.  It is installed as part of the ros-kinetic-desktop-full configuration or using the command:
$ sudo apt-get install ros-kinetic-vision-opencv ros-kinetic-opencv3

To check your version of OpenCV, use the following commands:
$ python
>>>  import cv2
>>>  cv2.__ _version_ __

The version output should be '3.3.1-dev'

**Comment by FairchildC** [comment]
Accidentally closed this issue.  If it is still an issue, please reopen.

**Comment by crazynirmal** [comment]
Thank you for the response.
I have followed the step as mention in the book.
So I have installed OpenCV version 3.3.1 and I also verify that as you
suggested. But still problem present.

I am trying to resolve the issue.
.

**Comment by crazynirmal** [comment]
I have found that the 'libfreenect2' design for Kinect windows v2. Is it possible that procedure, as mentioned in the book, will applicable for controlling crazyflie 2.0 with Kinect Xbox one sensor?

**Comment by FairchildC** [comment]
The Kinect Xbox One sensor uses libfreenect.     [https://github.com/OpenKinect/libfreenect](url)
